export { AlertCircleIcon } from './icons/AlertCircleIcon'
export { ContactIcon } from './icons/ContactIcon'
export { MapIcon } from './icons/MapIcon'
export { RewardIcon } from './icons/RewardIcon'
export { TimeIcon } from './icons/TimeIcon'
export { UserIcon } from './icons/UserIcon'
export { EllipseIcon } from './icons/EllipseIcon'
export { StarIcon } from './icons/StarIcon'
export { SearchIcon } from './icons/SearchIcon'
export { HeartIcon } from './icons/HeartIcon'
export { HelpIcon } from './icons/HelpIcon'
export { SadnessIcon } from './icons/SadnessIcon'
export { SettingsIcon } from './icons/SettingsIcon'
export { SmileIcon } from './icons/SmileIcon'
export { IdeaIcon } from './icons/IdeaIcon'
export { AddCircleIcon } from './icons/AddCircleIcon'
export { FilterIcon } from './icons/FilterIcon'
export { LeftIcon } from './icons/LeftIcon'
export { LocationIcon } from './icons/LocationIcon'
export { MobileIcon } from './icons/MobileIcon'
export { FacebookIcon } from './icons/FacebookIcon'
export { InstagramIcon } from './icons/InstagramIcon'
export { ShareIcon } from './icons/ShareIcon'
export { WhatsappIcon } from './icons/WhatsappIcon'
export { DownArrowIcon } from './icons/DownArrowIcon'
export { ImageIcon } from './icons/ImageIcon'
export { FrowningFaceIcon } from './icons/FrowningFaceIcon'
export { SmileyFaceIcon } from './icons/SmileyFaceIcon'
export { PolygonsIcon } from './icons/PolygonsIcon'
export { DogFaceIcon } from './icons/DogFaceIcon'
export { PhoneIcon } from './icons/PhoneIcon'
export { UpArrowIcon } from './icons/UpArrowIcon'
export { CancelIcon } from './icons/CancelIcon'
export { KeyIcon } from './icons/KeyIcon'
export { QuestionHelpIcon } from './icons/QuestionHelpIcon'
export { SuccessCheckIcon } from './icons/SuccessCheckIcon'

export * from './icons/custom'
// TODO: Preguntarle a Isaias si pudiese hacer que estos 2 íconos no vengan en grupo
export { default as GroupIcon } from './icons/Group.svg'
export { default as LogoIcon } from './icons/Logo.svg'
